// Mirrors contracts/riftcover.py exactly — do not diverge without updating both.

export const EVENT_CLASSES = [
  "SERVICE_WITHDRAWAL",
  "CAPABILITY_REMOVAL",
  "ENDPOINT_REMOVAL",
  "REGION_WITHDRAWAL",
  "COMMERCIAL_ACCESS_REMOVED",
  "MATERIAL_PRICE_INCREASE",
  "BACKWARD_INCOMPATIBLE_CHANGE",
  "LICENCE_RESTRICTION",
  "TERMS_PROHIBITION",
  "PROLONGED_DEGRADATION",
  "PROTOCOL_SUSPENSION",
  "MIGRATION_NOTICE_BREACH",
  "SECURITY_PAUSE",
  "NO_QUALIFYING_EVENT",
  "INSUFFICIENT_EVIDENCE",
  "CONFLICTING_EVIDENCE",
] as const;
export type EventClass = (typeof EVENT_CLASSES)[number];

export const SOURCE_CLASSES = [
  "OFFICIAL_ANNOUNCEMENT",
  "OFFICIAL_DOCUMENTATION",
  "OFFICIAL_STATUS_PAGE",
  "OFFICIAL_REPOSITORY",
  "OFFICIAL_CHANGELOG",
  "OFFICIAL_TERMS",
  "OFFICIAL_PRICING",
  "ARCHIVED_OFFICIAL_PAGE",
  "INDEPENDENT_AUTHORITATIVE_REPORT",
  "UNVERIFIED_SECONDARY",
] as const;
export type SourceClass = (typeof SOURCE_CLASSES)[number];

export const POLICY_STATUSES = [
  "DRAFT",
  "QUOTED",
  "AWAITING_PREMIUM",
  "WAITING_PERIOD",
  "ACTIVE",
  "EVENT_REPORTED",
  "EVIDENCE_OPEN",
  "UNDER_REVIEW",
  "DECISION_PROPOSED",
  "CHALLENGE_WINDOW",
  "FINALIZED_APPROVED",
  "FINALIZED_REJECTED",
  "FINALIZED_INCONCLUSIVE",
  "PAID",
  "EXPIRED",
  "CANCELLED",
] as const;
export type PolicyStatus = (typeof POLICY_STATUSES)[number];

export const CLAIM_STATUSES = [
  "SUBMITTED",
  "EVIDENCE_OPEN",
  "READY_FOR_REVIEW",
  "RESOLVING",
  "PROPOSED_APPROVED",
  "PROPOSED_REJECTED",
  "PROPOSED_INCONCLUSIVE",
  "CHALLENGED",
  "FINAL_APPROVED",
  "FINAL_REJECTED",
  "FINAL_INCONCLUSIVE",
  "PAYOUT_EXECUTED",
  "CLOSED",
] as const;
export type ClaimStatus = (typeof CLAIM_STATUSES)[number];

export const MAX_EVIDENCE_PER_CLAIM = 12;
export const MAX_DOMAINS = 20;
export const BASIS_POINTS_MAX = 10000;
